name: Php fixer commenter
on: [ push, pull_request ]

jobs:
    analyze:
        runs-on: composer
        steps:
            -   name: Analyze
                run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix -v --dry-run --format gitlab --using-cache no > $PHPCS_REPORT_JSON_PATH
            -   name: Archive code analysis results
                uses: actions/upload-artifact@v2
                with:
                    name: code-analysis-report
                    path: $PHPCS_REPORT_JSON_PATH
